package com.xnvalabs.xnai

/**
 * Curated, extensible catalog of programming languages and algorithm families.
 * This is a knowledge index, not an embedded compiler for every language.
 * New entries can be added without changing the UI.
 */

data class LanguageInfo(
    val name: String,
    val family: String,
    val paradigms: List<String>,
    val runtime: String,
    val strengths: String,
    val commonUses: String,
    val learningPath: List<String>
)

data class AlgorithmInfo(
    val name: String,
    val domain: String,
    val complexity: String,
    val idea: String,
    val steps: List<String>,
    val uses: String
)


data class ReasoningMethodInfo(
    val name: String,
    val mode: String,
    val purpose: String,
    val procedure: List<String>
)

object KnowledgeCatalog {
    val languages: List<LanguageInfo> = listOf(
        l("C", "Systems", "imperative, procedural", "native compiler", "control, performance, ABI", "embedded, kernels, native libraries", "types → memory → pointers → structs → concurrency"),
        l("C++", "Systems", "multi-paradigm, OOP, generic, functional", "native compiler", "performance, generic programming", "engines, finance, systems, games", "RAII → STL → templates → concurrency"),
        l("C#", ".NET", "OOP, generic, functional", ".NET", "productivity, tooling, async", "apps, backend, games", "types → LINQ → async → ASP.NET"),
        l("Java", "JVM", "OOP, generic, functional", "JVM", "portability, ecosystem, tooling", "backend, Android legacy, enterprise", "OOP → collections → JVM → concurrency"),
        l("Kotlin", "JVM / Android", "OOP, functional, declarative", "JVM / Native", "null-safety, coroutines, concise syntax", "Android, backend, multiplatform", "types → collections → coroutines → Compose"),
        l("Swift", "Apple", "OOP, protocol-oriented, functional", "native / Swift runtime", "safety, performance, Apple integration", "iOS, macOS, systems", "value types → protocols → async → SwiftUI"),
        l("Objective-C", "Apple / C", "OOP, imperative", "native runtime", "legacy Apple interoperability", "legacy Apple apps", "C → messages → runtime → Foundation"),
        l("Go", "Systems", "imperative, concurrent", "native compiler", "simple concurrency, deployment", "cloud, networking, tooling", "types → interfaces → goroutines → channels"),
        l("Rust", "Systems", "imperative, functional, generic", "native compiler", "memory safety, zero-cost abstractions", "systems, WebAssembly, tooling", "ownership → borrowing → traits → async"),
        l("Zig", "Systems", "imperative, metaprogramming", "native compiler", "low-level control, simple toolchain", "systems, embedded, tooling", "pointers → comptime → allocators → build"),
        l("D", "Systems", "multi-paradigm", "native compiler", "systems productivity", "native apps, tooling", "types → contracts → templates → ranges"),
        l("Nim", "Systems", "imperative, functional, metaprogramming", "native / C backend", "expressiveness with native output", "systems, scripting", "types → iterators → macros → FFI"),
        l("Python", "General-purpose", "imperative, OOP, functional", "CPython / alternatives", "rapid development, huge ecosystem", "AI, automation, data, backend", "syntax → data model → modules → async → typing"),
        l("Ruby", "General-purpose", "OOP, metaprogramming", "MRI / Ruby VM", "developer productivity, expressive DSLs", "web, automation", "objects → blocks → modules → metaprogramming"),
        l("PHP", "Web", "imperative, OOP", "Zend Engine", "web integration, deployment reach", "web backend, CMS", "syntax → arrays → OOP → HTTP → frameworks"),
        l("Perl", "Scripting", "imperative, functional, regex-centric", "Perl interpreter", "text processing, glue code", "legacy systems, text tools", "scalars → lists → regex → modules"),
        l("Lua", "Embedded scripting", "imperative, functional", "Lua VM", "small footprint, embeddability", "games, embedded apps", "tables → functions → metatables → embedding"),
        l("R", "Statistics", "functional, vectorized", "R runtime", "statistics, data analysis", "statistics, research, visualization", "vectors → data frames → functions → modeling"),
        l("Julia", "Scientific", "multiple dispatch, functional", "JIT / LLVM", "numerical computing, performance", "scientific computing, optimization", "multiple dispatch → arrays → types → performance"),
        l("MATLAB", "Scientific", "array-oriented, imperative", "MATLAB runtime", "matrix workflows, prototyping", "engineering, simulation", "arrays → plots → functions → toolboxes"),
        l("GNU Octave", "Scientific", "array-oriented", "interpreter", "MATLAB-like numerical work", "education, scientific computing", "arrays → plotting → numerical methods"),
        l("JavaScript", "Web", "prototype/OOP, functional, event-driven", "browser / JS runtime", "ubiquitous web platform", "web, Node.js, tooling", "types → closures → DOM → async → runtime APIs"),
        l("TypeScript", "Web", "typed JS, OOP, functional", "transpiles to JS", "static analysis at JS scale", "large web apps, tooling", "types → generics → narrowing → modules"),
        l("Dart", "UI / App", "OOP, async", "Dart VM / native / JS", "portable UI tooling", "Flutter apps, tooling", "types → async → isolates → Flutter"),
        l("Groovy", "JVM", "OOP, scripting, dynamic", "JVM", "DSLs and JVM scripting", "Gradle, automation", "closures → builders → DSLs → JVM"),
        l("Scala", "JVM", "OOP, functional", "JVM", "expressive types, functional abstractions", "data systems, backend", "types → FP → collections → concurrency"),
        l("F#", ".NET", "functional, OOP", ".NET", "functional modeling on .NET", "data, backend, finance", "discriminated unions → pattern matching → async"),
        l("Haskell", "Functional", "pure functional, lazy", "GHC", "strong abstractions, type safety", "research, compilers, backend", "types → purity → laziness → typeclasses"),
        l("OCaml", "Functional", "functional, imperative, OOP", "native / bytecode", "type inference, native performance", "compilers, formal tools", "variants → pattern matching → modules → functors"),
        l("Elixir", "BEAM", "functional, concurrent", "BEAM", "fault tolerance, concurrency", "distributed services, realtime", "immutability → processes → supervision → OTP"),
        l("Erlang", "BEAM", "functional, actor-like", "BEAM", "fault tolerance, distributed concurrency", "telecom, realtime", "processes → messages → supervision → OTP"),
        l("Gleam", "BEAM", "functional, typed", "BEAM", "typed functional concurrency", "distributed BEAM services", "types → pattern matching → actors"),
        l("Clojure", "Lisp / JVM", "functional, data-oriented", "JVM", "immutable data and macros", "backend, data tooling", "lists → persistent data → sequences → macros"),
        l("Common Lisp", "Lisp", "multi-paradigm, metaprogramming", "native / VM", "macros, dynamic programming", "AI history, tooling, DSLs", "s-expressions → functions → macros → objects"),
        l("Scheme", "Lisp", "functional, minimal", "various", "language research, elegant semantics", "education, interpreters", "lambda → recursion → continuations"),
        l("Racket", "Lisp", "functional, metaprogramming", "Racket VM", "language-oriented programming", "education, DSLs, research", "syntax objects → modules → macros"),
        l("Prolog", "Logic", "declarative, logic", "Prolog VM", "rules and search", "symbolic reasoning, constraint problems", "facts → rules → unification → backtracking"),
        l("Fortran", "Scientific", "imperative, array-oriented", "native compiler", "numerical performance", "HPC, scientific computing", "arrays → procedures → modules → parallelism"),
        l("COBOL", "Business", "imperative", "native / JVM / mainframe", "business data processing", "banking, mainframes", "records → files → procedural divisions"),
        l("Ada", "Safety / Systems", "imperative, generic", "native compiler", "safety, contracts, robustness", "aviation, defense, embedded", "types → packages → contracts → concurrency"),
        l("Pascal", "Education / Systems", "imperative, procedural", "native compiler", "structured programming", "education, legacy", "types → records → procedures → units"),
        l("Object Pascal", "Desktop", "OOP, imperative", "native compiler", "rapid desktop development", "Delphi applications", "classes → components → events"),
        l("Visual Basic .NET", ".NET", "OOP, imperative", ".NET", "rapid business apps", "desktop, enterprise", "forms → OOP → LINQ → async"),
        l("Bash", "Shell", "imperative, command composition", "shell", "OS automation", "DevOps, scripting", "commands → pipes → quoting → jobs"),
        l("PowerShell", "Shell / .NET", "object-pipeline, imperative", ".NET", "administration through objects", "Windows / cloud automation", "objects → pipeline → remoting → modules"),
        l("Zsh", "Shell", "imperative", "shell", "interactive shell productivity", "Unix automation", "expansion → functions → completion"),
        l("Fish", "Shell", "imperative", "shell", "interactive usability", "Unix automation", "commands → functions → scripting"),
        l("SQL", "Declarative", "declarative, relational", "database engine", "set-based data operations", "databases, analytics", "relations → joins → aggregation → windows"),
        l("PL/SQL", "Database", "procedural + SQL", "Oracle DB", "database-side logic", "Oracle applications", "SQL → blocks → cursors → packages"),
        l("T-SQL", "Database", "procedural + SQL", "SQL Server", "SQL Server programming", "enterprise databases", "queries → CTEs → windows → procedures"),
        l("Solidity", "Smart contracts", "contract-oriented", "EVM", "programmable blockchain state", "Ethereum-compatible contracts", "types → storage → events → security"),
        l("Vyper", "Smart contracts", "contract-oriented, Python-like", "EVM", "restricted smart contract design", "Ethereum contracts", "types → state → functions → security"),
        l("Move", "Smart contracts", "resource-oriented", "Move VM", "resource safety", "blockchain assets", "resources → abilities → modules → transactions"),
        l("Cairo", "Zero-knowledge", "constraint-oriented", "Cairo VM", "provable computation", "ZK applications", "felt arithmetic → traces → proofs"),
        l("Verilog", "HDL", "hardware description", "HDL simulator / synthesis", "digital hardware modeling", "FPGA, ASIC", "signals → combinational → sequential → testbench"),
        l("SystemVerilog", "HDL", "hardware + verification", "simulator / synthesis", "verification and RTL", "FPGA, ASIC", "RTL → assertions → interfaces → verification"),
        l("VHDL", "HDL", "strongly typed hardware description", "simulator / synthesis", "formal hardware modeling", "FPGA, ASIC", "entities → architectures → processes → verification"),
        l("GLSL", "GPU", "shader language", "GPU driver", "parallel graphics computation", "graphics shaders", "vectors → stages → textures → lighting"),
        l("HLSL", "GPU", "shader language", "GPU driver", "graphics and compute shaders", "DirectX graphics", "vectors → resources → stages → compute"),
        l("WGSL", "GPU", "shader language", "WebGPU", "portable web GPU programming", "WebGPU graphics", "types → bindings → compute/render"),
        l("CUDA C++", "GPU / NVIDIA", "imperative, parallel", "CUDA runtime", "general GPU compute", "AI, simulation, HPC", "threads → blocks → shared memory → kernels"),
        l("OpenCL C", "GPU / Heterogeneous", "imperative, parallel", "OpenCL runtime", "portable accelerator compute", "HPC, image processing", "kernels → workgroups → memory spaces"),
        l("GDScript", "Game", "OOP, imperative", "Godot VM", "game scripting", "Godot games", "nodes → signals → resources"),
        l("Raku", "Scripting", "multi-paradigm", "MoarVM", "expressive text and DSLs", "scripting, language experiments", "regex → grammars → roles → concurrency"),
        l("Crystal", "Compiled scripting", "OOP, static typing", "native compiler", "Ruby-like syntax with native code", "CLI, backend", "types → macros → concurrency"),
        l("Hack", "Web", "typed PHP-family", "HHVM", "large web codebases", "backend, legacy migration", "types → collections → async"),
        l("Vala", "GNOME", "OOP, C-like", "native compiler to C", "desktop integration", "GTK applications", "classes → async → GObject"),
        l("Dhall", "Configuration", "functional, typed", "interpreter", "safe configuration", "config generation", "types → records → imports"),
        l("Ballerina", "Integration", "typed, service-oriented", "Ballerina runtime", "network and integration workloads", "APIs, event systems", "records → services → workers → transactions"),
        l("Pony", "Actors / Systems", "actor, capability-secure", "native compiler", "concurrency safety", "systems, actors", "actors → capabilities → isolation"),
        l("Idris", "Dependent types", "functional, dependent", "native / VM", "proof-oriented programming", "formal methods, research", "types → dependent types → proofs"),
        l("Agda", "Dependent types", "functional, dependent", "Agda checker", "formalization and proofs", "theorem proving, research", "types → propositions → proofs"),
        l("Lean", "Theorem proving", "functional, dependent", "Lean compiler", "formal proofs and verified programming", "math, verification", "types → tactics → proofs → programs")
    ).sortedBy { it.name }

    val reasoningMethods: List<ReasoningMethodInfo> = listOf(
        rm("Deduktif", "Deduction", "Turunkan konsekuensi dari premis yang diterima.", "premis → aturan → konsekuensi → cek validitas"),
        rm("Induktif", "Induction", "Cari pola umum dari banyak observasi.", "kumpulkan data → cari pola → generalisasi → uji contoh baru"),
        rm("Abduktif", "Abduction", "Cari penjelasan paling masuk akal untuk observasi.", "observasi → kandidat sebab → ranking bukti → uji"),
        rm("First Principles", "Decomposition", "Kembali ke fakta dasar dan bangun ulang solusi.", "pecah asumsi → tetapkan fakta → bangun solusi"),
        rm("Falsifikasi", "Verification", "Aktif mencari kondisi yang akan meruntuhkan klaim.", "formalkan klaim → cari counterexample → uji batas"),
        rm("Causal Analysis", "Causality", "Pisahkan korelasi, mekanisme, dan confounder.", "observasi → hipotesis sebab → mekanisme → alternatif → uji"),
        rm("Bayesian Update", "Probabilistic", "Perbarui keyakinan saat bukti baru muncul.", "prior → likelihood → posterior → kalibrasi"),
        rm("Analogical Reasoning", "Transfer", "Pindahkan struktur dari domain sumber ke target.", "identifikasi struktur → mapping → cek kesetaraan → uji"),
        rm("Counterfactual", "Causal", "Tanya apa yang berubah bila satu kondisi diubah.", "tetapkan dunia awal → ubah satu variabel → bandingkan"),
        rm("Constraint Reasoning", "Constraint", "Persempit ruang solusi dengan aturan dan batas.", "definisikan variabel → domain → constraint → propagasi"),
        rm("Search", "Exploration", "Jelajahi ruang kemungkinan dan pangkas kandidat buruk.", "generate → score → prune → backtrack"),
        rm("Simulation", "Experiment", "Uji dunia model sebelum keputusan nyata.", "buat model → parameter → jalankan → ukur → ulang"),
        rm("Proof by Invariant", "Formal", "Cari properti yang tetap benar sepanjang proses.", "hipotesis invariant → base case → step → simpulkan"),
        rm("Error Analysis", "Debugging", "Gunakan kegagalan untuk menemukan penyebab sistemik.", "reproduce → isolate → hypothesis → fix → regression"),
        rm("Self-Refine", "Reflection", "Kritik dan revisi output beberapa putaran.", "draft → critique → revise → verify"),
        rm("Tool-Using Reasoning", "Agentic", "Gunakan alat untuk memperoleh observasi baru.", "plan → tool action → observe → update"),
        rm("Hypothesis Competition", "Scientific", "Biarkan beberapa penjelasan bersaing dengan evidence.", "generate → rank → test → eliminate/keep"),
        rm("Knowledge Graph Traversal", "Retrieval", "Hubungkan fakta melalui node dan relasi.", "seed → expand → filter → synthesize"),
        rm("Program Synthesis", "Computational", "Bangun program dari grammar lalu uji terhadap target.", "grammar → candidates → execute → score → prune"),
        rm("Red-Team Review", "Adversarial", "Cari kelemahan solusi sebelum dipakai.", "assume failure → attack assumptions → document fixes"),
        rm("Decision Theory", "Decision", "Pilih tindakan berdasarkan utility, risk, dan uncertainty.", "options → outcomes → probability → utility → choose"),
        rm("Information Gain", "Active Learning", "Pilih pertanyaan/eksperimen yang paling banyak mengurangi ketidakpastian.", "uncertainty → candidate query → expected gain → choose"),
        rm("Occam / Simplicity", "Model Selection", "Pilih penjelasan sederhana yang tetap menjelaskan bukti.", "fit candidates → compare complexity → prefer adequate simplicity"),
        rm("Minimum Description", "Compression", "Cari representasi ringkas yang mempertahankan informasi penting.", "encode → measure → compare → retain structure")
    )

    val algorithms: List<AlgorithmInfo> = listOf(
        a("Bubble Sort", "Sorting", "O(n²)", "Swap adjacent inverted elements repeatedly.", "scan → compare → swap → repeat", "teaching, tiny arrays"),
        a("Insertion Sort", "Sorting", "O(n²), best O(n)", "Grow a sorted prefix by inserting each next element.", "take key → shift larger → insert", "small or nearly sorted data"),
        a("Selection Sort", "Sorting", "O(n²)", "Select the next minimum and place it.", "find min → swap → advance", "simple teaching and tiny arrays"),
        a("Merge Sort", "Sorting", "O(n log n)", "Divide into halves, sort, and merge.", "split → recurse → merge", "stable external-friendly sorting"),
        a("Quick Sort", "Sorting", "average O(n log n)", "Partition around a pivot and recurse.", "choose pivot → partition → recurse", "general in-memory sorting"),
        a("Heap Sort", "Sorting", "O(n log n)", "Use a heap to repeatedly extract extrema.", "heapify → extract → restore", "in-place worst-case bounded sorting"),
        a("Counting Sort", "Sorting", "O(n+k)", "Count occurrences over a bounded integer range.", "count → prefix/count placement", "small integer domains"),
        a("Radix Sort", "Sorting", "O(d(n+k))", "Sort by successive digit positions.", "stable digit pass → repeat", "fixed-width integers and strings"),
        a("Bucket Sort", "Sorting", "average O(n+k)", "Distribute values into buckets then sort buckets.", "bucketize → sort buckets → concatenate", "uniform numeric distributions"),
        a("Binary Search", "Searching", "O(log n)", "Halve a sorted search interval each step.", "compare middle → discard half", "sorted arrays"),
        a("Linear Search", "Searching", "O(n)", "Scan elements until a match is found.", "visit → compare → stop", "unsorted collections"),
        a("Hash Lookup", "Searching", "expected O(1)", "Map keys to buckets using a hash function.", "hash → bucket → compare", "sets, maps, caches"),
        a("BFS", "Graphs", "O(V+E)", "Explore a graph layer by layer.", "queue start → visit neighbors → enqueue", "shortest unweighted paths"),
        a("DFS", "Graphs", "O(V+E)", "Explore deeply before backtracking.", "visit → recurse/stack → backtrack", "connectivity, cycle detection"),
        a("Dijkstra", "Graphs", "O((V+E)logV)", "Greedily expand the nearest tentative node with nonnegative weights.", "priority queue → relax edges → repeat", "weighted shortest path"),
        a("Bellman-Ford", "Graphs", "O(VE)", "Relax every edge repeatedly to handle negative edges.", "initialize → relax V-1 times → detect negative cycle", "negative-weight shortest path"),
        a("Floyd-Warshall", "Graphs", "O(V³)", "Dynamic programming over allowed intermediate vertices.", "initialize matrix → add intermediate k", "all-pairs shortest path"),
        a("A* Search", "Graphs", "depends on heuristic", "Best-first search guided by path cost plus heuristic.", "score f=g+h → expand best → relax", "pathfinding with good heuristics"),
        a("Topological Sort", "Graphs", "O(V+E)", "Order a DAG so edges go forward.", "compute indegree → queue zero-indegree → remove", "dependency planning"),
        a("Kruskal MST", "Graphs", "O(E log E)", "Add cheapest edges that do not create a cycle.", "sort edges → union-find → accept", "minimum spanning trees"),
        a("Prim MST", "Graphs", "O(E log V)", "Grow a spanning tree from a chosen root by cheapest frontier edge.", "priority queue → choose edge → add", "minimum spanning trees"),
        a("Union-Find", "Data Structures", "near O(1) amortized", "Maintain disjoint sets with path compression and union by rank.", "find representative → union representatives", "connectivity, Kruskal"),
        a("Dynamic Programming", "Optimization", "problem dependent", "Reuse solutions to overlapping subproblems.", "define state → recurrence → memo/tabulate", "sequence, scheduling, combinatorial optimization"),
        a("0/1 Knapsack", "Dynamic Programming", "O(nW)", "Choose items under a capacity constraint.", "state by item/capacity → take/skip", "resource allocation"),
        a("Longest Common Subsequence", "Strings", "O(nm)", "Track matching subsequences with a DP grid.", "compare chars → carry/max/match", "diff, sequence analysis"),
        a("Edit Distance", "Strings", "O(nm)", "Compute minimum insert/delete/replace edits.", "initialize borders → recurrence", "spell checking, fuzzy matching"),
        a("KMP", "Strings", "O(n+m)", "Use a prefix function to skip impossible matches.", "build prefix table → scan text", "exact substring search"),
        a("Boyer-Moore", "Strings", "sublinear average", "Skip ahead using character-based heuristics.", "align pattern → inspect right-to-left → shift", "fast text search"),
        a("Trie", "Strings / Data Structures", "O(length)", "Store strings along prefix-sharing paths.", "walk characters → create nodes", "autocomplete, dictionaries"),
        a("Heap", "Data Structures", "O(log n) update", "Maintain a partial order at a tree root.", "insert/extract → sift", "priority queues"),
        a("Monotonic Stack", "Sequences", "O(n)", "Keep a stack with monotone values to answer next-greater style queries.", "scan → pop invalid → push", "next greater, histogram"),
        a("Sliding Window", "Sequences", "usually O(n)", "Maintain a moving interval while updating aggregate state.", "expand → update → shrink", "subarray/string constraints"),
        a("Two Pointers", "Sequences", "usually O(n)", "Move two indices according to an invariant.", "initialize ends → move pointer", "sorted arrays, partitioning"),
        a("Prefix Sum", "Sequences", "O(n) preprocess", "Store cumulative totals for constant-time range sums.", "accumulate → subtract endpoints", "range queries"),
        a("Difference Array", "Sequences", "O(n)", "Encode interval updates by boundary deltas.", "mark starts/ends → prefix reconstruct", "batch range updates"),
        a("Fast Fourier Transform", "Numerical", "O(n log n)", "Factor a DFT into smaller transforms.", "split even/odd → butterfly combine", "signal processing, convolution"),
        a("Euclidean Algorithm", "Number Theory", "O(log min(a,b))", "Repeatedly replace the pair with remainder.", "a,b → b,a mod b → repeat", "GCD and number theory"),
        a("Extended Euclid", "Number Theory", "O(log n)", "Compute gcd plus Bezout coefficients.", "recurse/iterate remainders → back substitute", "modular inverses"),
        a("Sieve of Eratosthenes", "Number Theory", "O(n log log n)", "Mark multiples of each prime.", "start 2 → mark multiples → advance", "prime generation"),
        a("Fast Exponentiation", "Number Theory", "O(log n)", "Square the base while halving exponent.", "if odd multiply → square → halve", "powers, modular exponentiation"),
        a("Newton-Raphson", "Numerical", "iteration dependent", "Improve a root estimate using tangent-line corrections.", "evaluate f/f' → update x", "root finding, optimization"),
        a("Gradient Descent", "Optimization", "iteration dependent", "Move parameters opposite the gradient.", "compute loss → gradient → update", "machine learning, numerical optimization"),
        a("Newton Optimization", "Optimization", "iteration dependent", "Use first and second derivatives for parameter updates.", "gradient → Hessian → solve → update", "smooth optimization"),
        a("Simulated Annealing", "Optimization", "stochastic", "Occasionally accept worse states to escape local minima.", "propose → score → accept by temperature", "combinatorial optimization"),
        a("Genetic Algorithm", "Optimization", "stochastic", "Evolve candidate solutions using selection, crossover, mutation.", "initialize → evaluate → select → vary → repeat", "black-box optimization"),
        a("Beam Search", "Search", "depends on beam width", "Keep only the best partial candidates at each depth.", "expand → score → prune to beam", "sequence generation, planning"),
        a("Monte Carlo", "Simulation", "stochastic", "Estimate quantities by random sampling.", "sample → evaluate → aggregate", "risk, integration, uncertainty"),
        a("Markov Chain", "Probabilistic", "state dependent", "Model transitions using the current state.", "define states → transition → sample/analyze", "simulation, ranking"),
        a("Naive Bayes", "Machine Learning", "training dependent", "Classify with conditional-independence assumptions.", "estimate priors/likelihoods → combine", "text classification, baselines"),
        a("k-Nearest Neighbors", "Machine Learning", "O(n) query baseline", "Predict from labels of nearest examples.", "distance → sort/select k → vote/average", "classification, regression"),
        a("k-Means", "Machine Learning", "iteration dependent", "Alternate assignment and centroid updates.", "initialize centers → assign → update → repeat", "clustering"),
        a("Decision Tree", "Machine Learning", "training dependent", "Split data recursively using an impurity criterion.", "choose split → partition → recurse", "classification, regression"),
        a("Random Forest", "Machine Learning", "ensemble dependent", "Average many randomized decision trees.", "bootstrap → random features → fit trees → aggregate", "robust tabular baselines"),
        a("Gradient Boosting", "Machine Learning", "ensemble dependent", "Add weak models that correct previous residuals.", "fit residuals → add learner → repeat", "tabular prediction"),
        a("PCA", "Linear Algebra / ML", "O(nd²) typical", "Project data onto directions of maximal variance.", "center → covariance/SVD → project", "dimensionality reduction"),
        a("Linear Regression", "Statistics", "closed form / iterative", "Fit parameters minimizing squared error.", "build design matrix → solve least squares", "prediction, calibration"),
        a("Logistic Regression", "Statistics / ML", "iterative", "Fit a logistic decision boundary.", "sigmoid → likelihood → optimize", "binary classification"),
        a("PageRank", "Graphs", "iteration dependent", "Rank nodes using stationary random-walk behavior.", "initialize → distribute rank → normalize → iterate", "link analysis"),
        a("Minimax", "Game Search", "branching dependent", "Choose moves assuming an optimal opponent.", "generate moves → recurse → min/max back up", "adversarial search"),
        a("Alpha-Beta Pruning", "Game Search", "best case much lower than minimax", "Skip branches that cannot change the minimax decision.", "maintain alpha/beta → prune", "game engines"),
        a("Constraint Propagation", "Constraint Solving", "problem dependent", "Narrow variable domains before search.", "assign constraints → propagate reductions", "scheduling, puzzles"),
        a("Backtracking", "Search", "exponential worst case", "Build a partial solution and undo invalid choices.", "choose → test → recurse → undo", "CSP, permutations"),
        a("Branch and Bound", "Optimization", "problem dependent", "Prune partial solutions whose bounds cannot beat the best.", "branch → bound → prune/expand", "integer optimization"),
        a("Bisection", "Numerical", "O(log tolerance)", "Halve an interval containing a root.", "evaluate midpoint → keep sign-changing half", "robust root finding"),
        a("Gauss Elimination", "Linear Algebra", "O(n³)", "Eliminate coefficients to solve linear systems.", "pivot → eliminate → back substitute", "equation solving"),
        a("LU Decomposition", "Linear Algebra", "O(n³)", "Factor a matrix into lower and upper triangular components.", "eliminate → store factors", "repeated linear solves"),
        a("QR Decomposition", "Linear Algebra", "O(n³)", "Factor a matrix into orthogonal and triangular parts.", "orthogonalize → triangularize", "least squares, eigen methods"),
        a("SVD", "Linear Algebra", "O(mn min(m,n)) typical", "Factor a matrix into orthogonal singular vectors and singular values.", "factor → threshold/project", "PCA, compression, denoising"),
        a("RANSAC", "Computer Vision", "stochastic", "Fit a model robustly despite outliers.", "sample minimal set → fit → count inliers → repeat", "line/plane/model estimation"),
        a("Hough Transform", "Computer Vision", "parameter-space dependent", "Vote in parameter space for geometric primitives.", "edge points → parameter votes → peaks", "lines, circles"),
        a("Canny Edge Detection", "Computer Vision", "O(n) image pixels", "Detect edges through gradient, non-max suppression and hysteresis.", "blur → gradient → suppress → threshold/hysteresis", "shape and boundary extraction"),
        a("Connected Components", "Computer Vision", "O(n)", "Group adjacent foreground pixels into components.", "scan → label → merge/flood fill", "object blobs, segmentation"),
        a("Contour Approximation", "Computer Vision", "depends on contour", "Simplify a contour into fewer representative vertices.", "trace contour → simplify polyline", "shape recognition"),
        a("DCT", "Compression", "O(n log n) fast variants", "Represent signals as cosine basis coefficients.", "transform → quantize → encode", "image/audio compression"),
        a("Huffman Coding", "Compression", "O(n log n)", "Assign shorter codes to more frequent symbols.", "count → priority queue → merge tree", "lossless compression"),
        a("LZ77", "Compression", "implementation dependent", "Replace repeated sequences with back-references.", "find match → emit distance/length or literal", "DEFLATE-family compression"),
        a("LZ78", "Compression", "implementation dependent", "Build a dictionary of seen phrases.", "scan phrase → dictionary index → extend", "dictionary compression"),
        a("Arithmetic Coding", "Compression", "implementation dependent", "Encode symbols as intervals according to probabilities.", "probabilities → narrow interval → emit code", "entropy coding"),
        a("Burrows-Wheeler Transform", "Compression", "O(n log n) typical", "Reorder rotations to cluster repeated symbols.", "sort rotations → emit last column", "compression preprocessing"),
        a("AES", "Cryptography", "fixed-round", "Block cipher using substitution, permutation and key schedule.", "key expansion → rounds → inverse for decrypt", "confidentiality"),
        a("ChaCha20", "Cryptography", "fixed-round", "Stream cipher based on ARX operations.", "initialize state → rounds → keystream", "mobile/network encryption"),
        a("SHA-2", "Cryptography", "fixed-round", "Cryptographic hash construction.", "pad → compress blocks → output digest", "integrity, signatures"),
        a("SHA-3", "Cryptography", "sponge", "Keccak sponge construction.", "absorb → permute → squeeze", "hashing"),
        a("RSA", "Cryptography", "modular exponentiation", "Public-key cryptosystem based on modular arithmetic.", "keygen → modular powers → padding", "legacy public-key use, signatures"),
        a("Elliptic Curve Cryptography", "Cryptography", "group operations", "Use elliptic-curve group arithmetic for public-key systems.", "scalar multiplication → key exchange/signature", "modern key exchange/signatures"),
        a("Diffie-Hellman", "Cryptography", "modular/curve operations", "Derive a shared secret over a public channel.", "choose secret → exchange public value → combine", "key agreement"),
        a("Merkle Tree", "Data Integrity", "O(n) build", "Hash children into parent hashes recursively.", "hash leaves → pairwise hash → root", "integrity proofs, blockchains"),
        a("Bloom Filter", "Probabilistic DS", "O(k)", "Use multiple hashes to test set membership with false positives.", "hash item → set bits → query bits", "cache and database filtering"),
        a("Count-Min Sketch", "Streaming", "O(k)", "Estimate frequencies with hashed counters.", "hash → increment rows → min estimate", "stream analytics"),
        a("Reservoir Sampling", "Streaming", "O(n)", "Maintain a uniform sample from a stream of unknown length.", "fill reservoir → random replace", "sampling streams"),
        a("Consistent Hashing", "Distributed Systems", "O(log n) lookup typical", "Map keys around a hash ring to reduce remapping.", "hash nodes/keys → choose successor", "distributed caches"),
        a("Raft", "Distributed Systems", "protocol dependent", "Replicate a log with leader election and consensus.", "elect → append → replicate → commit", "distributed state"),
        a("MapReduce", "Distributed Data", "data dependent", "Split computation into map and reduce stages.", "partition → map → shuffle → reduce", "large-scale batch processing"),
        a("B+ Tree", "Databases", "O(log n)", "Balanced tree optimized for ordered disk access.", "search path → leaf → split/merge", "database indexes"),
        a("LSM Tree", "Databases", "amortized / workload dependent", "Batch writes into sorted structures and compact over time.", "memtable → flush → merge/compact", "write-heavy storage"),
        a("Query Planning", "Databases", "cost-model dependent", "Choose physical operators using statistics and cost estimates.", "parse → logical plan → enumerate → cost → execute", "SQL databases"),
        a("Lexing", "Compilers", "O(n)", "Convert characters into tokens.", "scan → classify → emit tokens", "compiler frontends"),
        a("Parsing", "Compilers", "grammar dependent", "Build structure from tokens using a grammar.", "tokens → productions → AST", "language processing"),
        a("Earley Parser", "Parsing", "O(n³) worst", "General CFG parser using chart states.", "predict → scan → complete", "general parsing"),
        a("CYK", "Parsing", "O(n³)", "Dynamic-programming parser for CNF grammars.", "fill chart spans → combine productions", "formal language parsing"),
        a("Register Allocation", "Compilers", "graph/problem dependent", "Assign values to a limited register set.", "liveness → interference graph → color/spill", "code generation"),
        a("Constant Folding", "Compilers", "linear-ish", "Evaluate compile-time expressions early.", "walk AST → identify constants → replace", "compiler optimization"),
        a("Dead Code Elimination", "Compilers", "graph dependent", "Remove code whose results cannot affect observable behavior.", "build CFG → liveness/reachability → remove", "compiler optimization"),
        a("Common Subexpression Elimination", "Compilers", "graph dependent", "Reuse equivalent expression results.", "identify expressions → track availability → reuse", "compiler optimization"),
        a("Partial Evaluation", "Compilers", "program dependent", "Specialize a program using known inputs.", "bind known values → simplify → residualize", "staging, specialization"),
        a("Autodiff", "Machine Learning / Calculus", "graph dependent", "Propagate derivatives through a computation graph.", "build graph → forward/reverse accumulate", "neural networks, optimization"),
        a("Beam-Tree Hybrid Search", "Reasoning", "bounded", "Explore several hypotheses while pruning low-value branches.", "expand → score → prune → backtrack", "agent reasoning"),
        a("Self-Refine Loop", "Reasoning", "iteration dependent", "Generate, critique, revise, and re-score an answer.", "draft → critique → revise → verify", "quality improvement"),
        a("ReAct Loop", "Reasoning", "iteration dependent", "Interleave reasoning with tool actions and observations.", "plan → act → observe → update", "tool-using agents"),
        a("Reflexion Loop", "Reasoning", "iteration dependent", "Store verbal feedback from previous trials to improve future attempts.", "attempt → feedback → reflection → retry", "trial-and-error agents"),
        a("Hypothesis Ranking", "Reasoning", "O(h log h)", "Rank candidate explanations by evidence, novelty, testability and cost.", "score → sort → keep top candidates", "scientific exploration"),
        a("Knowledge Graph Traversal", "Knowledge", "O(V+E)", "Explore concepts and relations as a graph.", "seed nodes → expand relations → collect evidence", "retrieval and synthesis"),
        a("Analogy Search", "Reasoning", "retrieval dependent", "Transfer structure from a known domain to a target problem.", "extract structure → map entities → test correspondence", "cross-domain invention"),
        a("Counterexample Search", "Reasoning", "search dependent", "Actively seek a case that would falsify a claim.", "formalize claim → generate boundary cases → test", "verification"),
        a("Invariant Discovery", "Reasoning", "search dependent", "Find properties preserved by a process.", "sample states → compare features → propose invariant → test", "proof and debugging"),
        a("Program Synthesis Search", "AI / Programming", "search dependent", "Search programs from a grammar and test cases.", "generate → execute → score → prune", "code generation")
    )

    private fun l(name: String, family: String, paradigms: String, runtime: String, strengths: String, uses: String, path: String) = LanguageInfo(
        name, family, paradigms.split(", "), runtime, strengths, uses, path.split(" → ")
    )

    private fun a(name: String, domain: String, complexity: String, idea: String, steps: String, uses: String) = AlgorithmInfo(
        name, domain, complexity, idea, steps.split(" → "), uses
    )

    private fun rm(name: String, mode: String, purpose: String, procedure: String) = ReasoningMethodInfo(
        name, mode, purpose, procedure.split(" → ")
    )
}
